/** @file

  Copyright (c) 2022, ARM Limited. All rights reserved.<BR>

  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

#ifndef CADENCE_QSPI_REG_H_
#define CADENCE_QSPI_REG_H_

// QSPI Controller defines
#define CDNS_QSPI_FLASH_CMD_CTRL_REG_OFFSET             0x90
#define CDNS_QSPI_FLASH_CMD_CTRL_REG_EXECUTE            0x01
#define CDNS_QSPI_FLASH_CMD_CTRL_REG_ADDR_ENABLE        0x01
#define CDNS_QSPI_FLASH_CMD_CTRL_REG_ADDR_BIT_POS       19
#define CDNS_QSPI_FLASH_CMD_CTRL_REG_ADDR_BYTE_BIT_POS  16
#define CDNS_QSPI_FLASH_CMD_CTRL_REG_STATUS_BIT         0x02
#define CDNS_QSPI_FLASH_CMD_CTRL_REG_OPCODE_BIT_POS     24
#define CDNS_QSPI_FLASH_CMD_CTRL_REG_READ_ENABLE        0x01
#define CDNS_QSPI_FLASH_CMD_CTRL_REG_READ_BYTE_3B       0x02
#define CDNS_QSPI_FLASH_CMD_CTRL_REG_READEN_BIT_POS     23
#define CDNS_QSPI_FLASH_CMD_CTRL_REG_READBYTE_BIT_POS   20
#define CDNS_QSPI_FLASH_CMD_CTRL_REG_DUMMY_8C           0x8
#define CDNS_QSPI_FLASH_CMD_CTRL_REG_DUMMY_BIT_POS      7
#define CDNS_QSPI_FLASH_CMD_CTRL_REG_NUM_DATA_BYTES(x)  ((x - 1) << CDNS_QSPI_FLASH_CMD_CTRL_REG_READBYTE_BIT_POS)
#define CDNS_QSPI_FLASH_CMD_CTRL_REG_NUM_ADDR_BYTES(x)  ((x - 1) << CDNS_QSPI_FLASH_CMD_CTRL_REG_ADDR_BYTE_BIT_POS)

#define CDNS_QSPI_FLASH_CMD_READ_DATA_REG_OFFSET  0xA0

#define CDNS_QSPI_FLASH_CMD_ADDR_REG_OFFSET  0x94

#endif /* CADENCE_QSPI_REG_H_ */
