; @file
;
; AMD Generic Encapsulated Software Architecture
; Workfile: AmdUefiStackNasm.inc
; $Revision$    $Date$
; Description: Code to setup temporary memory access for stack usage. This code
; is to be used on memory present systems that do not need CAR
; 
;  Copyright (C) 2008-2025 Advanced Micro Devices, Inc. All rights reserved.<BR>
;
;  SPDX-License-Identifier: BSD-2-Clause-Patent
;
%macro AMD_ENABLE_UEFI_STACK2 2-3

%endmacro
